---

- hosts: all
  any_errors_fatal: true
  ignore_unreachable: yes
  become: true
  become_user: root
  tasks:
    - include: tasks/debian.yml
    - include: tasks/setup.yml
    - include: tasks/consul.yml
    - include: tasks/rabbitmq.yml
    - include: tasks/postgresql.yml
    - include: tasks/freeswitch.yml
    - include: tasks/rtpengine.yml
    - include: tasks/opensips.yml
    - include: tasks/webitel.yml
    - include: tasks/grafana.yml
    - include: tasks/nginx.yml
    - include: tasks/letsencrypt.yml

  handlers:
    - include: handlers/main.yml
