---
- name: Add FreeSWITCH apt-key
  apt_key:
    url: https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc
    state: present

- name: Add FreeSWITCH repository into sources list
  apt_repository:
    repo:  deb http://files.freeswitch.org/repo/deb/debian-release/ {{ hostvars[inventory_hostname].ansible_distribution_release }} main
    state: present
    filename: freeswitch

- name: Update repositories cache and install FreeSWITCH 1.10.7 packages
  apt:
    name:
      - freeswitch=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-av=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-opus=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-opusfile=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-sndfile=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-shout=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-sofia=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-dialplan-xml=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-valet-parking=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-conference=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-console=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-event-socket=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-loopback=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-commands=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-db=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-dptools=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-expr=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-hash=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-spandsp=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-imagick=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-png=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-native-file=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-logfile=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-local-stream=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-tone-stream=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-lua=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-http-cache=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-spy=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-mod-json-cdr=1.10.7~release~19~883d2cb662~buster-1~buster+1
      - freeswitch-music-default
      - freeswitch-systemd
      - librabbitmq4
      - imagemagick
    install_recommends: no
    update_cache: yes

- name: Create cache directory
  file:
    dest: /var/cache/freeswitch
    state: directory
    owner: freeswitch
    group: freeswitch
    mode: 0777

- name: Read bootstrapped state
  stat:
    path: /etc/freeswitch/.bootstrap
  register: bootstrap_state
  ignore_errors: true
  tags: always

- name: Install Webitel modules for FreeSWITCH
  unarchive:
    src: "https://releases.webitel.com/{{ webitel_ver }}/{{ item }}"
    dest: /usr/lib/freeswitch/mod/
    remote_src: yes
  notify: restart FreeSWITCH
  with_items:
    - mod_amd-FS-1.10.7-release.zip
    - mod_amqp-FS-1.10.7-release.zip
    - mod_grpc-FS-1.10.7-release.zip
    - mod_google_transcribe-FS-1.10.7-release.zip

- name: Download FreeSWITCH configure
  get_url:
    url: "https://git.webitel.com/projects/WEP/repos/freeswitch/raw/{{ item }}"
    dest: "/etc/freeswitch/{{ item }}"
  with_items:
    - mime.types
    - configuration.xml
    - freeswitch.xml
    - vars.xml
  when: not bootstrap_state.stat.exists

- name: Change outbound SIP Proxy IP
  replace:
    path: /etc/freeswitch/vars.xml
    after: '<X-PRE-PROCESS cmd="set" data="outbound_sip_proxy='
    before: '"/>'
    regexp: '^(.+)$'
    replace: '{{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] }}'
  when: not bootstrap_state.stat.exists

- name: Enable Freeswitch at startup (systemd)
  systemd:
    name: freeswitch
    enabled: yes
    state: started
  when:
    - ansible_service_mgr == "systemd"

- name: Create bootstrapped state file
  file:
    dest: /etc/freeswitch/.bootstrap
    state: touch
  notify: restart FreeSWITCH
  when: not bootstrap_state.stat.exists
