---
- name: Add PostgreSQL apt-key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository into sources list
  apt_repository:
    repo:  deb http://apt.postgresql.org/pub/repos/apt/ {{ hostvars[inventory_hostname].ansible_distribution_release }}-pgdg main
    state: present
    filename: postgresql

- name: Add TimescaleDB apt-key
  apt_key:
    url: https://packagecloud.io/timescale/timescaledb/gpgkey
    state: present

- name: Add TimescaleDB repository into sources list
  apt_repository:
    repo: deb https://packagecloud.io/timescale/timescaledb/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} main
    state: present
    filename: timescaledb

- name: Update repositories cache and install PostgreSQL 14 and timescaledb packages
  apt:
    pkg:
      - postgresql-14
      - webitel-postgresql-14
      - timescaledb-2-postgresql-14
    update_cache: yes

- name: Execute timescaledb-tune
  shell: timescaledb-tune --quiet --yes

- name: Restart PostgreSQL on Linux
  service:
    name: postgresql
    state: restarted

- name: Enable PostgreSQL at startup (systemd)
  systemd:
    name: postgresql
    enabled: yes
  when:
    - ansible_service_mgr == "systemd"

- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: restart postgresql
  when: systemd_unit is changed

- name: Create "opensips" user, set password, grant privs
  postgresql_user:
    name: opensips
    password: webitel
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Create a new database with name "webitel"
  postgresql_db:
    name: webitel
    owner: opensips
  register: create_db
  become_user: postgres

- name: Download database schema
  get_url:
    url: "https://git.webitel.com/projects/WEP/repos/postgres/raw/{{ item }}?at=refs%2Ftags%2F{{ webitel_ver }}"
    dest: /tmp/{{ item }}
    mode: 0777
  become_user: postgres
  with_items:
    - webitel-db-schema.sql
    - webitel-db-data.sql
  when:
    - create_db is changed

- name: Restore database "webitel" from the file
  postgresql_db:
    name: webitel
    owner: opensips
    state: restore
    target: "{{ item }}"
  with_items:
    - /tmp/webitel-db-schema.sql
    - /tmp/webitel-db-data.sql
  become_user: postgres
  when: create_db is changed

- name: Delete downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/webitel-db-schema.sql
    - /tmp/webitel-db-data.sql
  when: create_db is changed

- name: Download pgsql vacuum script
  get_url:
    url: "https://git.webitel.com/projects/WEP/repos/postgres/raw/cc_vacuum.sql"
    dest: "/var/lib/postgresql/cc_vacuum.sql"
    mode: 0777
  become_user: postgres

- name: Creates a cron file under /etc/cron.d
  ansible.builtin.cron:
    name: psql cc_vacuum
    minute: "4"
    hour: "4"
    user: postgres
    job: "psql webitel < ~/cc_vacuum.sql"
    cron_file: ansible_psql-cc_vacuum

