---
- name: Add rabbitmq apt-key
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present

- name: Add rabbitmq repository into sources list
  apt_repository:
    repo:  deb https://dl.bintray.com/rabbitmq/debian {{ hostvars[inventory_hostname].ansible_distribution_release }} main
    state: present
    filename: rabbitmq

- name: Add rabbitmq-erlang repository into sources list
  apt_repository:
    repo: deb https://dl.bintray.com/rabbitmq-erlang/debian {{ hostvars[inventory_hostname].ansible_distribution_release }} erlang
    state: present
    filename: rabbitmq-erlang

- name: Update repositories cache and install "rabbitmq-server" package
  apt:
    name: rabbitmq-server
    update_cache: yes

- name: get rabbitmq version
  command: rabbitmqctl version
  register: rabbitmq_version

- name: Read bootstrapped state
  stat:
    path: /etc/rabbitmq/.bootstrap
  register: bootstrap_state
  ignore_errors: true
  tags: always

- name: Download "rabbitmq_delayed_message_exchange"
  get_url:
    url: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez
    dest: /usr/lib/rabbitmq/lib/rabbitmq_server-{{rabbitmq_version.stdout}}/plugins/rabbitmq_delayed_message_exchange-3.8.0.ez
  notify: restart rabbitmq-server

- name: Create rabbitmq-service directory
  file:
    dest: /etc/systemd/system/rabbitmq-server.service.d
    state: directory
  register: systemd_unit

- name: Add rabbitmq limits
  template:
    src: "templates/rabbitmq_systemd.limits.conf"
    dest: "/etc/systemd/system/rabbitmq-server.service.d/limits.conf"
  notify: restart rabbitmq-server

- name: Download "rabbitmq plugins"
  get_url:
    url: https://git.webitel.com/projects/WEP/repos/rabbitmq/raw/enabled_plugins
    dest: /etc/rabbitmq/enabled_plugins
  when: not bootstrap_state.stat.exists

- name: Download "rabbitmq config"
  get_url:
    url: https://git.webitel.com/projects/WEP/repos/rabbitmq/raw/rabbitmq.conf
    dest: /etc/rabbitmq/rabbitmq.conf
  when: not bootstrap_state.stat.exists

- name: Enable rabbitmq at startup (systemd)
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started
  when:
    - ansible_service_mgr == "systemd"

- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: restart rabbitmq-server
  when: systemd_unit is changed

- name: add webitel user
  command: rabbitmqctl add_user webitel webitel
  when: not bootstrap_state.stat.exists

- name: become an administrator
  command: rabbitmqctl set_user_tags webitel administrator
  when: not bootstrap_state.stat.exists

- name: set permissions for webitel user
  command: rabbitmqctl set_permissions -p / webitel ".*" ".*" ".*"
  when: not bootstrap_state.stat.exists

- name: delete guest user
  command: rabbitmqctl delete_user guest
  when: not bootstrap_state.stat.exists

- name: Create bootstrapped state file
  file:
    dest: /etc/rabbitmq/.bootstrap
    state: touch
  notify: restart rabbitmq-server
  when: not bootstrap_state.stat.exists
