---
# Common roles for all hosts
- name: Updates apt cache & upgrades dist
  apt:
    upgrade: 'yes'
    update_cache: 'yes'

- name: 'Install all necessary software with APT'
  apt:
    name:
      - acl
      - curl
      - wget
      - unzip
      - gnupg
      - locales
      - dnsutils
      - python3-psycopg2
    state: latest
    update_cache: yes
    install_recommends: no

- name: Fetch Webitel GPG key
  apt_key:
    url: http://deb.webitel.com/archive.key
    state: present

- name: Add Webitel repo
  apt_repository:
    repo: deb http://deb.webitel.com/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} main
    state: present
    update_cache: 'no'
    filename: webitel

- name: Add Webitel releases repo
  apt_repository:
    repo: deb http://deb.webitel.com/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} {{ webitel_ver }}-releases
    state: present
    filename: webitel
    update_cache: 'no'
  when: webitel_ver != 'dev'

- name: Add Webitel dev repo
  apt_repository:
    repo: deb http://deb.webitel.com/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} {{ webitel_ver }}
    state: present
    filename: webitel
    update_cache: 'no'
  when: webitel_ver == 'dev'

- name: Add Webitel NEXT releases repo
  apt_repository:
    repo: deb http://deb.webitel.com/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} 22.07-releases
    state: present
    filename: webitel
    update_cache: 'no'
  when: webitel_ver == 'dev'

- locale_gen:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ locales_gen }}'

- sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: fs.file-max
    value: '1000000'
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes
    state: present
    reload: yes
