---
- name: Install webitel binary
  unarchive:
    src: https://releases.webitel.com/builds/webitel-linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Read bootstrapped state
  stat:
    path: /var/run/webitel/.bootstrap
  register: bootstrap_state
  ignore_errors: true
  tags: always

- name: Clone webitel files
  git:
    repo: 'https://git.webitel.com/scm/wep/webitel.git'
    dest: /opt/webitel
  when: not bootstrap_state.stat.exists

- name: Create webitel run directory
  file:
    dest: /var/run/webitel
    state: directory
  when: not bootstrap_state.stat.exists

- name: Copy files
  copy:
    src: /opt/webitel/webitel/
    dest: /var/lib/webitel/
    remote_src: yes
  when: not bootstrap_state.stat.exists

- name: Copy default etc file
  copy:
    src: /opt/webitel/etc/default/webitel
    dest: /etc/default/webitel
    remote_src: yes
  when: not bootstrap_state.stat.exists

- name: Change SIP IP
  replace:
    path: /etc/default/webitel
    regexp: '(1\.1\.1\.1)$'
    replace: '{{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] }}'
  when: not bootstrap_state.stat.exists

- name: Copy webitel systemd files
  copy:
    src: '/opt/webitel/etc/systemd/system/{{ item }}'
    dest: /etc/systemd/system/
    remote_src: yes
  with_items:
    - webitel-api.service
    - webitel-app.service
    - webitel-dsa.service
    - webitel-uac.service
  when:
    - ansible_service_mgr == "systemd"
    - not bootstrap_state.stat.exists

- name: Enable webitel at startup (systemd)
  systemd:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - webitel-api.service
    - webitel-app.service
    - webitel-dsa.service
    - webitel-uac.service
  when:
    - ansible_service_mgr == "systemd"

- name: Create bootstrapped state file
  file:
    dest: /var/run/webitel/.bootstrap
    state: touch
  notify: restart webitel
  when: not bootstrap_state.stat.exists
